pool:
  vmImage: 'windows-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)\.m2\repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  - checkout: self
    clean: 'true'
    fetchDepth: '1'

  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)"'
      path: $(MAVEN_CACHE_FOLDER)
    displayName: 'Cache Maven local repo'

  - script: |
      echo ON
      choco install openjdk --no-progress
      call refreshenv
      echo ON
      call mvn -version
      call mvn install:install-file -Dfile=lib\ffmpeg-0.6.3-SNAPSHOT.jar -DpomFile=lib\pom.xml --no-transfer-progress $(MAVEN_OPTS)
      call mvn clean package -Dexec.skip=true --no-transfer-progress $(MAVEN_OPTS)
      echo OFF
    displayName: 'Build app without installer'
